# Generated by Django 4.2.5 on 2023-11-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0002_alter_gradescores_initial_grades_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                default="/static/star-admin/default_profile_img.jpg",
                upload_to="profile_images/",
            ),
        ),
    ]
