# Generated by Django 4.2.7 on 2024-03-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='performance_task_percentage',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='quarterly_assessment_percentage',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='written_works_percentage',
        ),
        migrations.AddField(
            model_name='archivedgradescores',
            name='grade_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradescores',
            name='grade_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='assessment',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
