# Generated by Django 4.2.7 on 2024-02-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradescores",
            name="Teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CuyabSRMS.teacher",
            ),
        ),
    ]
