# Generated by Django 4.2.7 on 2024-02-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnersObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_1', models.JSONField(null=True)),
                ('quarter_2', models.JSONField(null=True)),
                ('quarter_3', models.JSONField(null=True)),
                ('quarter_4', models.JSONField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_record', models.JSONField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
            ],
        ),
    ]
