# Generated by Django 4.2.7 on 2024-03-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0002_inboxmessage_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedmessage",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CuyabSRMS.mt",
            ),
        ),
        migrations.AddField(
            model_name="inboxmessage",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_messages",
                to="CuyabSRMS.mt",
            ),
        ),
    ]
