# Generated by Django 4.2.7 on 2024-02-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0002_student_class_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="class_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
