# Generated by Django 4.2.7 on 2024-02-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0002_learnersobservation_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddocument',
            name='user',
        ),
        migrations.AddField(
            model_name='processeddocument',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher'),
        ),
    ]
