# Generated by Django 4.2.6 on 2023-10-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0002_alter_gradescores_initial_grades_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracteddata',
            old_name='school_id',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='division',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='grade_section',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='region',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='school_name',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='general_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='lrn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='processed_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.processeddocument'),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='school_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
