# Generated by Django 4.2.7 on 2024-02-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0002_gradescores_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradescores",
            name="Teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="GradeScores",
                to="CuyabSRMS.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="gradescores",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="GradeScores",
                to="CuyabSRMS.student",
            ),
        ),
    ]
