# Generated by Django 4.2.7 on 2024-02-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0003_alter_gradescores_teacher_alter_gradescores_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradescores",
            name="Teacher",
        ),
        migrations.AlterField(
            model_name="gradescores",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CuyabSRMS.student"
            ),
        ),
    ]
