# Generated by Django 4.2.6 on 2023-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0003_rename_school_id_extracteddata_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddata',
            name='grade',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='classified_as_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='school_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
