# Generated by Django 4.2.7 on 2024-03-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0003_archivedstudent_archived_age_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.admin'),
            preserve_default=False,
        ),
    ]
