# Generated by Django 4.2.7 on 2024-03-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0004_rename_timestamp_inboxmessage_date_received_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inboxmessage",
            old_name="accepted",
            new_name="approved",
        ),
        migrations.RenameField(
            model_name="inboxmessage",
            old_name="date_accepted",
            new_name="date_approved",
        ),
        migrations.RemoveField(
            model_name="inboxmessage",
            name="accepted_by",
        ),
        migrations.AddField(
            model_name="inboxmessage",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_messages",
                to="CuyabSRMS.mt",
            ),
        ),
    ]
