# Generated by Django 4.2.7 on 2024-03-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0004_teacher_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='admin',
        ),
    ]
