# Generated by Django 4.2.6 on 2023-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0004_remove_extracteddata_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='general_average',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
