# Generated by Django 4.2.7 on 2024-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0004_restorerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaverage',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
