# Generated by Django 4.2.7 on 2024-02-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0004_remove_gradescores_teacher_alter_gradescores_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalgrade",
            name="subject",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
