# Generated by Django 4.2.7 on 2024-04-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0005_alter_feedback_rating'),
        ('CuyabSRMS', '0005_remove_teacher_admin'),
    ]

    operations = [
    ]
