# Generated by Django 4.2.6 on 2023-11-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0005_alter_extracteddata_general_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='name_of_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
