# Generated by Django 4.2.7 on 2024-02-12 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0005_finalgrade_subject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InboxMessage",
        ),
    ]
