# Generated by Django 4.2.7 on 2024-02-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0005_finalgrade_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("section", models.CharField(blank=True, max_length=50, null=True)),
                ("subject", models.CharField(blank=True, max_length=50, null=True)),
                ("quarters", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "from_teacher_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("student", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "initial_grades",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transmuted_grades",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
