# Generated by Django 4.2.7 on 2024-02-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0005_alter_inboxmessage_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxmessage",
            name="file_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
