# Generated by Django 4.2.7 on 2024-03-02 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0005_rename_accepted_inboxmessage_approved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acceptedmessage",
            old_name="reviewed_by",
            new_name="approved_by",
        ),
    ]
