# Generated by Django 4.2.7 on 2024-03-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0006_rename_reviewed_by_acceptedmessage_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedmessage",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CuyabSRMS.teacher",
            ),
        ),
    ]
