# Generated by Django 4.2.7 on 2024-02-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0006_advisoryclass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxmessage",
            name="from_teacher",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
