# Generated by Django 4.2.7 on 2024-02-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0006_inboxmessage_file_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inboxmessage",
            old_name="teacher",
            new_name="from_teacher",
        ),
        migrations.AddField(
            model_name="inboxmessage",
            name="to_teacher",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
