# Generated by Django 4.2.7 on 2024-03-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0006_corevalues_behavioralstatement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BehavioralStatement',
            new_name='BehaviorStatement',
        ),
    ]
