# Generated by Django 4.2.7 on 2024-02-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0007_advisoryclass_inboxmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advisoryclass",
            old_name="initial_grades",
            new_name="first_quarter",
        ),
        migrations.RenameField(
            model_name="advisoryclass",
            old_name="quarters",
            new_name="fourth_quarter",
        ),
        migrations.RenameField(
            model_name="advisoryclass",
            old_name="transmuted_grades",
            new_name="second_quarter",
        ),
        migrations.AddField(
            model_name="advisoryclass",
            name="third_quarter",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
