# Generated by Django 4.2.7 on 2024-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0007_rename_behavioralstatement_behaviorstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformation',
            name='principal_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corevalues',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
