# Generated by Django 4.2.7 on 2024-02-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0007_rename_teacher_inboxmessage_from_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxmessage",
            name="from_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CuyabSRMS.teacher"
            ),
        ),
    ]
