# Generated by Django 4.2.7 on 2024-03-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0007_acceptedmessage_accepted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="mt",
            name="assigned_grades",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
