# Generated by Django 4.2.6 on 2023-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0007_alter_gradescores_quarterly_assessment_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('written_works_percentage', models.PositiveIntegerField(default=40)),
                ('performance_task_percentage', models.PositiveIntegerField(default=40)),
                ('quarterly_assessment_percentage', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
