# Generated by Django 4.2.5 on 2023-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0008_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_quarter', models.PositiveIntegerField(default=40)),
                ('second_quarter', models.PositiveIntegerField(default=40)),
                ('third_quarter', models.PositiveIntegerField(default=40)),
                ('fourth_quarter', models.PositiveIntegerField(default=40)),
            ],
        ),
    ]
