# Generated by Django 4.2.6 on 2023-11-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0008_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_quarter', models.PositiveIntegerField(default=40)),
                ('second_quarter', models.PositiveIntegerField(default=40)),
                ('third_quarter', models.PositiveIntegerField(default=40)),
                ('fourth_quarter', models.PositiveIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
            ],
        ),
    ]
