# Generated by Django 4.2.7 on 2023-11-08 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0008_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
