# Generated by Django 4.2.7 on 2024-03-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0008_mt_assigned_grades"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedMessage",
            fields=[
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("json_data", models.JSONField()),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="CuyabSRMS.mt",
                    ),
                ),
            ],
        ),
    ]
