# Generated by Django 4.2.7 on 2024-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0008_alter_inboxmessage_from_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="lrn",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("lrn", "teacher")},
        ),
    ]
