# Generated by Django 4.2.6 on 2023-11-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0008_subject'),
        ('CuyabSRMS', '0009_alter_activitylog_timestamp'),
    ]

    operations = [
    ]
