# Generated by Django 4.2.7 on 2024-03-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0009_approvedmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvedmessage",
            name="to_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CuyabSRMS.teacher",
            ),
        ),
    ]
