# Generated by Django 4.2.7 on 2024-02-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0010_remove_advisoryclass_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedMessage",
            fields=[
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("json_data", models.JSONField()),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
