# Generated by Django 4.2.5 on 2023-11-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0010_rename_first_quarter_quarters_quarters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarters',
            name='quarters',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
