# Generated by Django 4.2.5 on 2023-10-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0010_gradescores_percentage_score_performance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="processed_documents/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("division", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "school_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("school_id", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "grade_section",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                (
                    "processed_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CuyabSRMS.processeddocument",
                    ),
                ),
            ],
        ),
    ]
