# Generated by Django 4.2.7 on 2024-03-05 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0010_approvedmessage_to_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acceptedmessage",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="inboxmessage",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="inboxmessage",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="inboxmessage",
            name="date_approved",
        ),
        migrations.DeleteModel(
            name="ApprovedMessage",
        ),
    ]
