# Generated by Django 4.2.7 on 2023-11-09 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0009_alter_activitylog_timestamp"),
        ("CuyabSRMS", "0009_quarters_classrecord"),
        ("CuyabSRMS", "0011_alter_quarters_quarters"),
    ]

    operations = []
