# Generated by Django 4.2.5 on 2023-10-23 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0011_processeddocument_extracteddata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processeddocument",
            name="user",
        ),
        migrations.DeleteModel(
            name="ExtractedData",
        ),
        migrations.DeleteModel(
            name="ProcessedDocument",
        ),
    ]
