# Generated by Django 4.2.7 on 2024-02-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0011_acceptedmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryclass",
            name="first_quarter",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="advisoryclass",
            name="fourth_quarter",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="advisoryclass",
            name="second_quarter",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="advisoryclass",
            name="third_quarter",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
