# Generated by Django 4.2.6 on 2023-11-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0012_merge_20231109_2032'),
    ]

    operations = [

    ]
