# Generated by Django 4.2.6 on 2023-11-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0012_gradescores_grade_gradescores_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher'),
            preserve_default=False,
        ),
    ]
