# Generated by Django 4.2.6 on 2023-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0012_merge_20231116_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarters',
            name='first_quarter',
        ),
        migrations.RemoveField(
            model_name='quarters',
            name='fourth_quarter',
        ),
        migrations.RemoveField(
            model_name='quarters',
            name='second_quarter',
        ),
        migrations.RemoveField(
            model_name='quarters',
            name='third_quarter',
        ),
        migrations.AddField(
            model_name='quarters',
            name='quarters',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
