# Generated by Django 4.2.7 on 2024-02-18 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0013_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
