# Generated by Django 4.2.5 on 2023-11-22 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0013_alter_classrecord_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradescores',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='gradescores',
            name='section',
        ),
        migrations.AddField(
            model_name='gradescores',
            name='class_record_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='GradeScores', to='CuyabSRMS.classrecord'),
            preserve_default=False,
        ),
    ]
