# Generated by Django 4.2.5 on 2023-11-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0014_remove_gradescores_grade_remove_gradescores_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradescores',
            old_name='class_record_id',
            new_name='class_record',
        ),
    ]
