# Generated by Django 4.2.5 on 2024-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0014_announcement_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('school_year', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_type',
        ),
    ]
