# Generated by Django 4.2.6 on 2023-12-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0015_rename_class_record_id_gradescores_class_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescores',
            name='scores_hps',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradescores',
            name='total_hps',
            field=models.FloatField(default=0),
        ),
    ]
