# Generated by Django 4.2.5 on 2024-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0015_schoolinformation_remove_section_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
