# Generated by Django 4.2.5 on 2023-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0016_gradescores_scores_hps_gradescores_total_hps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradescores',
            old_name='scores_hps',
            new_name='scores_hps_performance',
        ),
        migrations.AddField(
            model_name='gradescores',
            name='scores_hps_quarterly',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradescores',
            name='scores_hps_written',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
