# Generated by Django 4.2.5 on 2024-02-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0016_section_class_type_student_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='school_year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Subject_Teacher_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('quarter_grade', models.JSONField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Quarterly_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Adviser_Teacher_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lrn', models.CharField(max_length=12)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.CharField(default='N/A', max_length=10)),
                ('school_id', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_year', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_teachers', models.JSONField(null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
            ],
            options={
                'unique_together': {('lrn', 'teacher')},
            },
        ),
    ]
