# Generated by Django 4.2.5 on 2024-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0017_classrecord_school_year_subject_teacher_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
