# Generated by Django 4.2.5 on 2023-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0017_rename_scores_hps_gradescores_scores_hps_performance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradescores',
            old_name='total_hps',
            new_name='total_pt_hps',
        ),
        migrations.AddField(
            model_name='gradescores',
            name='total_qa_hps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gradescores',
            name='total_ww_hps',
            field=models.FloatField(default=0),
        ),
    ]
