# Generated by Django 4.2.5 on 2023-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0018_rename_total_hps_gradescores_total_pt_hps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescores',
            name='total_pt_hps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_qa_hps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_ww_hps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
