# Generated by Django 4.2.5 on 2024-02-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0018_alter_student_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_type',
            field=models.JSONField(null=True),
        ),
    ]
