# Generated by Django 4.2.5 on 2024-02-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0019_alter_student_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='class_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
