# Generated by Django 4.2.5 on 2023-12-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0019_alter_gradescores_total_pt_hps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescores',
            name='initial_grades',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='percentage_score_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='percentage_score_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='percentage_score_written',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_max_score_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_max_score_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_max_score_written',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_score_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_score_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_score_written',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='transmuted_grades',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weighted_score_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weighted_score_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weighted_score_written',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
