# Generated by Django 4.2.5 on 2023-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0020_alter_gradescores_initial_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescores',
            name='weigh_input_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradescores',
            name='weigh_input_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradescores',
            name='weigh_input_written',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
