# Generated by Django 4.2.5 on 2023-12-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0021_gradescores_weigh_input_performance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradescores',
            old_name='weigh_input_performance',
            new_name='weight_input_performance',
        ),
        migrations.RenameField(
            model_name='gradescores',
            old_name='weigh_input_quarterly',
            new_name='weight_input_quarterly',
        ),
        migrations.RenameField(
            model_name='gradescores',
            old_name='weigh_input_written',
            new_name='weight_input_written',
        ),
    ]
