# Generated by Django 4.2.5 on 2024-02-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0022_remove_advisoryclass_first_quarter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedAdvisoryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('grades_data', models.JSONField(blank=True, null=True)),
                ('date_archived', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'class_type': 'advisory'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='archivedclassrecord',
            name='school_year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='archived_class_type',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Adviser_Teacher_Class',
        ),
        migrations.DeleteModel(
            name='Quarterly_Grade',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Subject_Teacher_Class',
        ),
    ]
