# Generated by Django 4.2.5 on 2023-12-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0022_rename_weigh_input_performance_gradescores_weight_input_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('quarter1', models.FloatField()),
                ('quarter2', models.FloatField()),
                ('quarter3', models.FloatField()),
                ('quarter4', models.FloatField()),
                ('final_grade', models.FloatField()),
                ('class_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.classrecord')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
            ],
        ),
    ]
