# Generated by Django 4.2.5 on 2023-12-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0023_finalgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalgrade',
            name='class_record',
        ),
    ]
