# Generated by Django 4.2.5 on 2023-12-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0024_remove_finalgrade_class_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='quarters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.quarters'),
            preserve_default=False,
        ),
    ]
