# Generated by Django 4.2.5 on 2024-02-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0024_advisoryclass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedstudent',
            name='archived_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher'),
        ),
    ]
