# Generated by Django 4.2.6 on 2023-12-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0026_alter_classrecord_quarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgrade',
            name='grade_scores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.gradescores'),
            preserve_default=False,
        ),
    ]
