# Generated by Django 4.2.6 on 2023-12-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0027_finalgrade_grade_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgrade',
            name='grade_scores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.gradescores'),
        ),
    ]
