# Generated by Django 4.2.6 on 2023-12-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0028_alter_finalgrade_grade_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalgrade',
            name='quarter1',
        ),
        migrations.RemoveField(
            model_name='finalgrade',
            name='quarter2',
        ),
        migrations.RemoveField(
            model_name='finalgrade',
            name='quarter3',
        ),
        migrations.RemoveField(
            model_name='finalgrade',
            name='quarter4',
        ),
    ]
