# Generated by Django 4.2.6 on 2023-12-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0029_remove_finalgrade_quarter1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalgrade',
            name='grade_scores',
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='quarter1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='quarter2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='quarter3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='quarter4',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
