# Generated by Django 4.2.6 on 2023-12-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0030_remove_finalgrade_grade_scores_finalgrade_quarter1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('general_average', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
            ],
        ),
    ]
