# Generated by Django 4.2.6 on 2023-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0032_alter_generalaverage_general_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalaverage',
            name='student',
        ),
        migrations.AddField(
            model_name='generalaverage',
            name='student_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
