# Generated by Django 4.2.5 on 2023-12-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0035_gradescores_quarterly_assessment_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradescores',
            name='quarterly_assessment_scores',
        ),
        migrations.RemoveField(
            model_name='gradescores',
            name='scores_hps_quarterly',
        ),
    ]
