# Generated by Django 4.2.7 on 2024-01-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0036_remove_gradescores_quarterly_assessment_scores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classrecord",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
