# Generated by Django 4.2.5 on 2024-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0037_alter_gradescores_initial_grades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescores',
            name='initial_grades',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='percentage_score_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='percentage_score_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='percentage_score_written',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_max_score_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_max_score_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_max_score_written',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_score_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_score_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='total_score_written',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='transmuted_grades',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weight_input_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weight_input_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weight_input_written',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weighted_score_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weighted_score_quarterly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescores',
            name='weighted_score_written',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
