# Generated by Django 4.2.5 on 2024-01-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0038_alter_gradescores_initial_grades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradescores',
            name='student_name',
        ),
        migrations.AddField(
            model_name='gradescores',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student'),
            preserve_default=False,
        ),
    ]
