# Generated by Django 4.2.7 on 2024-01-19 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0037_classrecord_date_modified"),
        ("CuyabSRMS", "0039_remove_gradescores_student_name_gradescores_student"),
    ]

    operations = []
