# Generated by Django 4.2.5 on 2024-01-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0041_remove_finalgrade_student_name_finalgrade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalaverage',
            name='student_name',
        ),
        migrations.AddField(
            model_name='generalaverage',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student'),
            preserve_default=False,
        ),
    ]
