# Generated by Django 4.2.7 on 2024-01-25 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "CuyabSRMS",
            "0041_student_district_student_division_student_school_id_and_more",
        ),
        ("CuyabSRMS", "0042_remove_generalaverage_student_name_and_more"),
    ]

    operations = []
