# Generated by Django 4.2.6 on 2024-01-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0043_quarterlygrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterlygrades',
            name='grades',
            field=models.JSONField(null=True),
        ),
    ]
