# Generated by Django 4.2.7 on 2024-01-28 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0043_merge_20240125_2212"),
        ("CuyabSRMS", "0044_alter_quarterlygrades_grades"),
    ]

    operations = []
