# Generated by Django 4.2.7 on 2024-01-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0045_merge_20240128_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
