# Generated by Django 4.2.5 on 2024-01-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0046_remove_finalgrade_quarter1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedClassRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('quarters', models.CharField(blank=True, max_length=50, null=True)),
                ('date_archived', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
            ],
        ),
    ]
