# Generated by Django 4.2.7 on 2024-01-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0046_alter_grade_name_alter_section_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="grade_section",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
