# Generated by Django 4.2.7 on 2024-01-29 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0045_merge_20240128_1145"),
        ("CuyabSRMS", "0047_teacher_grade_section"),
    ]

    operations = []
