# Generated by Django 4.2.5 on 2024-01-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0047_archivedclassrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedGradeScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores_hps_written', models.JSONField()),
                ('scores_hps_performance', models.JSONField()),
                ('total_ww_hps', models.FloatField(blank=True, null=True)),
                ('total_pt_hps', models.FloatField(blank=True, null=True)),
                ('total_qa_hps', models.FloatField(blank=True, null=True)),
                ('written_works_scores', models.JSONField()),
                ('performance_task_scores', models.JSONField()),
                ('initial_grades', models.FloatField(blank=True, null=True)),
                ('transmuted_grades', models.FloatField(blank=True, null=True)),
                ('total_score_written', models.FloatField(blank=True, null=True)),
                ('total_max_score_written', models.FloatField(blank=True, null=True)),
                ('total_score_performance', models.FloatField(blank=True, null=True)),
                ('total_max_score_performance', models.FloatField(blank=True, null=True)),
                ('total_score_quarterly', models.FloatField(blank=True, null=True)),
                ('total_max_score_quarterly', models.FloatField(blank=True, null=True)),
                ('percentage_score_written', models.FloatField(blank=True, null=True)),
                ('percentage_score_performance', models.FloatField(blank=True, null=True)),
                ('percentage_score_quarterly', models.FloatField(blank=True, null=True)),
                ('weight_input_written', models.FloatField(blank=True, null=True)),
                ('weight_input_performance', models.FloatField(blank=True, null=True)),
                ('weight_input_quarterly', models.FloatField(blank=True, null=True)),
                ('weighted_score_written', models.FloatField(blank=True, null=True)),
                ('weighted_score_performance', models.FloatField(blank=True, null=True)),
                ('weighted_score_quarterly', models.FloatField(blank=True, null=True)),
                ('archived_class_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_gradescores', to='CuyabSRMS.archivedclassrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
            ],
        ),
    ]
