# Generated by Django 4.2.5 on 2024-01-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0048_archivedgradescores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_name', models.CharField(max_length=255)),
                ('archived_lrn', models.CharField(max_length=12)),
                ('archived_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('archived_birthday', models.CharField(default='N/A', max_length=10)),
                ('archived_school_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archived_division', models.CharField(blank=True, max_length=255, null=True)),
                ('archived_district', models.CharField(blank=True, max_length=255, null=True)),
                ('archived_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('archived_school_year', models.CharField(blank=True, max_length=50, null=True)),
                ('archived_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('archived_section', models.CharField(blank=True, max_length=50, null=True)),
                ('archived_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
                ('original_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archived_student', to='CuyabSRMS.student')),
            ],
        ),
    ]
