# Generated by Django 4.2.7 on 2024-01-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0048_merge_20240129_1251"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finalgrade",
            name="quarter1",
        ),
        migrations.RemoveField(
            model_name="finalgrade",
            name="quarter2",
        ),
        migrations.RemoveField(
            model_name="finalgrade",
            name="quarter3",
        ),
        migrations.RemoveField(
            model_name="finalgrade",
            name="quarter4",
        ),
        migrations.RemoveField(
            model_name="finalgrade",
            name="subject",
        ),
        migrations.AddField(
            model_name="section",
            name="total_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="finalgrade",
            name="final_grade",
            field=models.JSONField(),
        ),
    ]
