# Generated by Django 4.2.6 on 2024-01-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0049_archivedstudent_archivedfinalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedgradescores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.archivedstudent'),
        ),
        migrations.CreateModel(
            name='ArchivedQuarterlyGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_quarter', models.CharField(max_length=100)),
                ('archived_grades', models.JSONField(null=True)),
                ('archived_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedGeneralAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_grade', models.CharField(max_length=50)),
                ('archived_section', models.CharField(max_length=50)),
                ('archived_general_average', models.FloatField(blank=True, null=True)),
                ('archived_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
            ],
        ),
    ]
