# Generated by Django 4.2.7 on 2024-01-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0049_remove_finalgrade_quarter1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classrecord",
            name="grade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="CuyabSRMS.grade",
            ),
        ),
        migrations.AlterField(
            model_name="classrecord",
            name="section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="CuyabSRMS.section",
            ),
        ),
    ]
