# Generated by Django 4.2.5 on 2024-01-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0049_archivedstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_grade', models.CharField(max_length=50)),
                ('archived_section', models.CharField(max_length=50)),
                ('archived_final_grade', models.JSONField()),
                ('archived_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.student')),
                ('archived_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.teacher')),
                ('original_final_grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archived_final_grade', to='CuyabSRMS.finalgrade')),
            ],
        ),
    ]
