# Generated by Django 4.2.7 on 2024-01-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0050_alter_classrecord_grade_alter_classrecord_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="classrecord",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="classrecord",
            name="division",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="classrecord",
            name="school_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="classrecord",
            name="school_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="classrecord",
            name="school_year",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
