# Generated by Django 4.2.5 on 2024-01-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0050_archivedfinalgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedstudent',
            name='original_student',
        ),
    ]
