# Generated by Django 4.2.6 on 2024-01-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0050_alter_archivedgradescores_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedfinalgrade',
            name='original_final_grade',
        ),
    ]
