# Generated by Django 4.2.7 on 2024-01-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CuyabSRMS", "0051_classrecord_district_classrecord_division_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classrecord",
            name="district",
        ),
        migrations.RemoveField(
            model_name="classrecord",
            name="division",
        ),
        migrations.RemoveField(
            model_name="classrecord",
            name="school_id",
        ),
        migrations.RemoveField(
            model_name="classrecord",
            name="school_name",
        ),
        migrations.RemoveField(
            model_name="classrecord",
            name="school_year",
        ),
        migrations.AlterField(
            model_name="classrecord",
            name="grade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="classrecord",
            name="section",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
