# Generated by Django 4.2.6 on 2024-01-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0051_remove_archivedfinalgrade_original_final_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedfinalgrade',
            name='archived_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.archivedstudent'),
        ),
        migrations.AlterField(
            model_name='archivedgeneralaverage',
            name='archived_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.archivedstudent'),
        ),
        migrations.AlterField(
            model_name='archivedquarterlygrades',
            name='archived_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuyabSRMS.archivedstudent'),
        ),
    ]
