# Generated by Django 4.2.6 on 2024-02-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0048_merge_20240129_1251'),
        ('CuyabSRMS', '0052_alter_archivedfinalgrade_archived_student_and_more'),
    ]

    operations = [
    ]
