# Generated by Django 4.2.5 on 2024-02-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0054_section_total_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddocument',
            name='user',
        ),
    ]
