# Generated by Django 4.2.5 on 2024-02-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0055_remove_processeddocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
