# Generated by Django 4.2.5 on 2024-02-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuyabSRMS', '0056_processeddocument_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('school_year', models.CharField(max_length=100)),
            ],
        ),
    ]
